import { getServerSession } from "next-auth";
import { redirect, notFound } from "next/navigation";
import { authOptions } from "@/lib/auth";
import { listUserBusinesses } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import { PrintButton } from "./print-button";
import { InvoiceButton } from "./invoice-button";
import { formatDateTimeIn, resolveTimeZone } from "@/lib/timezone";

// A downloadable PDF (spec section 6) is now generated by the shared layout
// engine in src/lib/pdf.ts (Module 15) – browser print remains available
// too, since it's still the fastest path at a till with no internet.
export default async function ReceiptPage(props: { params: Promise<{ saleId: string }> }) {
  const params = await props.params;
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) redirect("/login");

  const memberships = await listUserBusinesses(session.user.id);
  if (memberships.length === 0) redirect("/dashboard");

  const sale = await prisma.sale.findUnique({
    where: { id: params.saleId },
    include: { items: { include: { product: true } }, customer: true, receipt: true, business: true },
  });

  const allowedBusinessIds = memberships.map((m) => m.businessId);
  if (!sale || !allowedBusinessIds.includes(sale.businessId)) notFound();
  const tz = resolveTimeZone(sale.business.timezone);

  return (
    <main className="mx-auto max-w-md p-8">
      <div className="mb-4 flex justify-end gap-2 print:hidden">
        <a
          href={`/api/business/${sale.businessId}/sales/${sale.id}/receipt/pdf`}
          target="_blank"
          rel="noopener noreferrer"
          className="rounded-md border border-gray-300 px-4 py-2 text-sm hover:bg-gray-100"
        >
          Download PDF
        </a>
        {Number(sale.balance) > 0 && <InvoiceButton businessId={sale.businessId} saleId={sale.id} />}
        <PrintButton />
      </div>

      <div className="rounded-md border bg-white p-6 text-sm">
        <div className="mb-4 text-center">
          <h1 className="text-lg font-bold">{sale.business.name}</h1>
          <p className="text-gray-600">{sale.business.physicalAddress ?? `${sale.business.city}, ${sale.business.district}`}</p>
          <p className="text-gray-600">{sale.business.phone}</p>
        </div>

        <div className="mb-3 flex justify-between border-y py-2 text-xs text-gray-500">
          <span>Receipt: {sale.receipt?.receiptNumber ?? "–"}</span>
          <span>{formatDateTimeIn(sale.saleDate, tz)}</span>
        </div>

        <p className="mb-2">Customer: {sale.customer?.name ?? "Walk-in"}</p>

        <table className="w-full text-xs">
          <thead>
            <tr className="border-b text-left">
              <th className="py-1">Item</th>
              <th className="py-1 text-right">Qty</th>
              <th className="py-1 text-right">Price</th>
              <th className="py-1 text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            {sale.items.map((item) => (
              <tr key={item.id} className="border-b">
                <td className="py-1">{item.product.name}</td>
                <td className="py-1 text-right">{Number(item.quantity)}</td>
                <td className="py-1 text-right">{Number(item.unitPrice).toLocaleString()}</td>
                <td className="py-1 text-right">{Number(item.total).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="mt-3 space-y-1 text-xs">
          <div className="flex justify-between"><span>Subtotal</span><span>MWK {Number(sale.subtotal).toLocaleString()}</span></div>
          <div className="flex justify-between"><span>Discount</span><span>-MWK {Number(sale.discount).toLocaleString()}</span></div>
          <div className="flex justify-between"><span>VAT</span><span>+MWK {Number(sale.tax).toLocaleString()}</span></div>
          <div className="flex justify-between border-t pt-1 font-semibold"><span>Total</span><span>MWK {Number(sale.total).toLocaleString()}</span></div>
          <div className="flex justify-between"><span>Paid ({sale.paymentMethod.replace("_", " ")})</span><span>MWK {Number(sale.amountPaid).toLocaleString()}</span></div>
          {Number(sale.balance) > 0 && (
            <div className="flex justify-between font-semibold text-red-700"><span>Balance due</span><span>MWK {Number(sale.balance).toLocaleString()}</span></div>
          )}
        </div>

        <p className="mt-4 text-center text-xs text-gray-400">Thank you for your business.</p>
      </div>
    </main>
  );
}
